---
# Source: airflow/templates/triggerer/triggerer-service.yaml
################################
## Airflow triggerer Service
#################################
apiVersion: v1
kind: Service
metadata:
  name: release-name-triggerer
  labels:
    tier: airflow
    component: triggerer
    release: release-name
    chart: "airflow-1.13.0"
    heritage: Helm
spec:
  clusterIP: None
  selector:
    tier: airflow
    component: triggerer
    release: release-name
  ports:
    - name: triggerer-logs
      protocol: TCP
      port: 8794
      targetPort: 8794
