---
# Source: airflow/templates/triggerer/triggerer-serviceaccount.yaml
################################
## Airflow Triggerer ServiceAccount
#################################
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: release-name-airflow-triggerer
  labels:
    tier: airflow
    component: triggerer
    release: release-name
    chart: "airflow-1.13.0"
    heritage: Helm
