---
# Source: airflow/templates/rbac/pod-log-reader-role.yaml
################################
## Airflow Pod Reader Role
#################################
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-name-pod-log-reader-role
  namespace: "default"
  labels:
    tier: airflow
    release: release-name
    chart: "airflow-1.13.0"
    heritage: Helm
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "list"
      - "get"
      - "watch"
  - apiGroups:
      - ""
    resources:
      - "pods/log"
    verbs:
      - "get"
      - "list"
