---
# Source: airflow/templates/workers/worker-service.yaml
################################
## Airflow Worker Service
#################################
apiVersion: v1
kind: Service
metadata:
  name: release-name-worker
  labels:
    tier: airflow
    component: worker
    release: release-name
    chart: "airflow-1.13.0"
    heritage: Helm
spec:
  clusterIP: None
  selector:
    tier: airflow
    component: worker
    release: release-name
  ports:
    - name: worker-logs
      protocol: TCP
      port: 8793
      targetPort: 8793
