---
# Source: airflow/templates/statsd/statsd-serviceaccount.yaml
######################################
## Airflow StatsD ServiceAccount
######################################
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: release-name-airflow-statsd
  labels:
    tier: airflow
    component: statsd
    release: release-name
    chart: "airflow-1.13.0"
    heritage: Helm
