---
# Source: airflow/templates/jobs/create-user-job-serviceaccount.yaml
###########################################
## Airflow Create User Job ServiceAccount
###########################################
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: release-name-airflow-create-user-job
  labels:
    tier: airflow
    component: create-user-job
    release: release-name
    chart: "airflow-1.13.0"
    heritage: Helm
