---
# Source: airflow/templates/jobs/migrate-database-job-serviceaccount.yaml
#############################################
## Airflow Migrate Database Job ServiceAccount
##############################################
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: release-name-airflow-migrate-database-job
  labels:
    tier: airflow
    component: run-airflow-migrations
    release: release-name
    chart: "airflow-1.13.0"
    heritage: Helm
