apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s"  .Values.streamlit.name .Values.ENV | quote }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ printf "%s-%s"  .Values.streamlit.name .Values.ENV | quote }}
  template:
    metadata:
      labels:
        app: {{ printf "%s-%s"  .Values.streamlit.name .Values.ENV | quote }}
    spec:
      containers:
      - name: {{ .Values.streamlit.name }}
        image: {{ .Values.streamlit.image.repository }}:{{ .Values.image.tag }}
        env:
          - name: APIURL
            value: {{printf "http://%s-%s:%s" .Values.api.name .Values.ENV .Values.api.service.port | quote }}
          - name: STREAMLIT_SERVER_PORT
            value: {{ .Values.streamlit.service.port | quote }}
        imagePullPolicy: {{ .Values.streamlit.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.streamlit.service.targetPort }}
        resources:
          limits:
            cpu: 30m
            ephemeral-storage: 100Mi
            memory: 100Mi
          requests:
            cpu: 30m
            ephemeral-storage: 100Mi
            memory: 100Mi
