apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s"  .Values.grafana.name .Values.ENV | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ printf "%s-%s"  .Values.grafana.name .Values.ENV | quote }}
  template:
    metadata:
      labels:
        app: {{ printf "%s-%s"  .Values.grafana.name .Values.ENV | quote }}
    spec:
      containers:
      - name: {{ .Values.grafana.name }}
        image: {{ .Values.grafana.image.repository }}
        env:
        - name:  GF_SMTP_ENABLED
          value: {{ .Values.grafana.env.GF_SMTP_ENABLED | quote }}
        - name:  GF_SMTP_HOST
          value: {{ .Values.grafana.env.GF_SMTP_HOST }}
        - name:  GF_SMTP_USER
          value: {{ .Values.grafana.env.GF_SMTP_USER | b64dec }}
        - name:  GF_SMTP_PASSWORD
          value: {{ .Values.grafana.env.GF_SMTP_PASSWORD | b64dec | quote }}
        - name:  GF_SMTP_SKIP_VERIFY
          value: {{ .Values.grafana.env.GF_SMTP_SKIP_VERIFY | quote }}
        - name:  GF_SMTP_FROM_ADDRESS
          value: {{ .Values.grafana.env.GF_SMTP_FROM_ADDRESS }}
        - name:  GF_SMTP_FROM_NAME
          value: {{ .Values.grafana.env.GF_SMTP_FROM_NAME }}
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: {{ .Values.grafana.name }}-volume-{{ .Values.ENV }}
        imagePullPolicy:  {{ .Values.grafana.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.grafana.service.targetPort }}
        resources:
          limits:
            cpu: 30m
            ephemeral-storage: 100Mi
            memory: 100Mi
          requests:
            cpu: 30m
            ephemeral-storage: 100Mi
            memory: 100Mi
      volumes:
      - name: {{ .Values.grafana.name }}-volume-{{ .Values.ENV }}
        emptyDir:
          sizeLimit: 500Mi

  