apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movieflix-ingress
spec:
  rules:
  - http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
             service:
              name: nginx
              port: 
                number: 80
        