apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movieflix-ingress
spec:
  rules:
  - http:
      paths:
        - path: {{ .Values.api.ingress.path}}
          pathType: Prefix
          backend:
             service:
              name: {{ .Values.api.name}}
              port: 
                number: {{ .Values.api.service.port}}
  - http:
      paths:
        - path: {{ .Values.streamlit.ingress.path}}
          pathType: Prefix
          backend:
             service:
              name: {{ .Values.streamlit.name}}
              port: 
                number: {{ .Values.streamlit.service.port}}