apiVersion: v1
kind: Service
metadata:
  name: {{printf "%s-%s" .Values.api.name .Values.ENV | quote }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - port: {{ .Values.api.service.port }}
    targetPort: {{ .Values.api.service.targetPort }}
    protocol: TCP
  selector:
    app: {{printf "%s-%s" .Values.api.name .Values.ENV | quote }}
