apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movieflix-ingress-streamlit-{{.Values.ENV }}
spec:
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
             service:
              name: {{printf "%s-%s" .Values.streamlit.name .Values.ENV | quote }}
              port: 
                number: {{.Values.streamlit.service.port }}