apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: autoriser-airflow-dev-vers-movieflix-dev
  namespace: movieflix-dev
spec:
  podSelector:
    matchLabels:
      app: {{ printf "%s-%s"  .Values.database.name .Values.ENV | quote }}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: airflow-dev
    ports:
    - port: 5431