apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s"  .Values.prometheus.name .Values.ENV | quote }}
  labels:
    {{- include "reco-film.labels" . | nindent 4 }}
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: {{ .Values.prometheus.service.targetPort }}
      nodePort:  {{  .Values.prometheus.service.nodePort }}
      protocol: TCP
  selector:
    app: {{ printf "%s-%s"  .Values.prometheus.name .Values.ENV | quote }}
