---
# Source: airflow/templates/secrets/metadata-connection-secret.yaml
################################
## Airflow Metadata Secret
#################################
apiVersion: v1
kind: Secret
metadata:
  name: release-name-metadata
  labels:
    tier: airflow
    release: release-name
    chart: airflow
    heritage: Helm
type: Opaque
data:
  connection: "cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHJlbGVhc2UtbmFtZS1wb3N0Z3Jlc3FsLmRlZmF1bHQ6NTQzMi9wb3N0Z3Jlcz9zc2xtb2RlPWRpc2FibGU="
